### ISSUE TITLE
Meeting Notes 1

### ISSUE THREAD

**Issue by yukseleren** [bounswe/bounswe2024group1#10]
Documenting the first meeting according to the template

**Comment by yukseleren** [comment]
Meeting notes added [here](https://github.com/bounswe/bounswe2024group1/wiki/Meeting-Notes#--date-18022024)

**Comment by mmtftr** [comment]
Can we move it into a new page and then link it inside [Meeting Notes](https://github.com/bounswe/bounswe2024group1/wiki/Meeting-Notes) as done in [Assignments](https://github.com/bounswe/bounswe2024group1/wiki/Assignments)
