### ISSUE TITLE
Implement Feed Page UI

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#120]
# 📌 Feature request 
## 📝 Description
First, implement recipe card. 
Then, make two lists of recipe cards for "Following" and "Explore", put them in tabs.

## 📈 Motivation
Want the users to look through the Feed Page and see recipes.

**Comment by mmtftr** [comment]
This issue is only for the UI, can you update the description and title?

**Comment by mmtftr** [comment]
This depends on #146

**Comment by NazireAta** [comment]
Closed due to #196
