### ISSUE TITLE
Database Mapping Implementation Tracker

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#127]
# 🔍 Issue Tracker

## 📝 Description
Monitor the implementation progress of Database Mappings in the project.

## 📅 Deadline
12.05.2024

## 🎯 Issues

1.  **User - Recipe Mappings**
    - [ ] **username - author:** one-to-many relationship
2.  **Dish -Cuisine Mappings**
3.  **Recipe - Dish Mappings**

**Comment by NazireAta** [comment]
Closed due to new term
