### ISSUE TITLE
Implement DELETE /recipes/{recipeId}/comments/{commentId}/upvote

### ISSUE THREAD

**Issue by EnesBaserr** [bounswe/bounswe2024group1#177]
# 📌 Feature request 
## 📝 Description
Implementing DELETE /recipes/{recipeId}/comments/{commentId}/upvote

## 📈 Motivation
A user can delete upvote for a comment.

**Comment by Cgtycolak** [comment]
Done with the following [commit](https://github.com/bounswe/bounswe2024group1/commit/d0fa130d2bc150994f0501e38de9593b1e4d0591)
