### ISSUE TITLE
Infinite Recursion Problem in Comment Entity

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#190]
I tested the endpoint but encountered an infinite recursion in the response, probably caused by mappings. Let me solve the problem before merging this.

_Originally posted by @atakanyasar in https://github.com/bounswe/bounswe2024group1/issues/188#issuecomment-2105853949_

**Comment by atakanyasar** [comment]
The suggested solution is [here](https://github.com/bounswe/bounswe2024group1/pull/188#issuecomment-2105903164)

**Comment by boraykasap** [comment]
[This](https://github.com/bounswe/bounswe2024group1/pull/188) updated
