### ISSUE TITLE
Unit Test Tracker

### ISSUE THREAD

**Issue by boraykasap** [bounswe/bounswe2024group1#258]
# 🔍 Issue Tracker

## 📝 Description
Implement unit tests
## 📅 Deadline
17.05.2024

## 👀 Reviewers
@EnesBaserr 
@atakanyasar 

## 🎯 Issues

1.  UnitTests
    -  [x] #233
    -  [x] #255
    - [x] Authentication Controller Unit Test 
    -  [x] #260 
    -  [x] #261
    -  [x] #262
    - [x] #311

**Comment by NazireAta** [comment]
Closed due to new term
