### ISSUE TITLE
Document favorite repos on GitHub

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#3]
>  Explore GitHub to discover some repositories that you like. Document at least one of them by providing a reference to the repo and describing what you liked about it.

Please open a new issue in the same style as #14 and add it to the list below.

- [x] #14 
- [x] #15 
- [x] #16 
- [x] #17 
- [x] #26 
- [x] #28 
- [x] #31 
- [x] #35
- [x] #39

**Comment by NazireAta** [comment]
Cool one! Doesn't have a wiki but has a detailed readme file and good examples for issues
https://github.com/facefusion/facefusion

**Comment by mmtftr** [comment]
Please put your favorite repositories in this wiki page using the provided template: [Favorite Github Repos](https://github.com/bounswe/bounswe2024group1/wiki/Team-Members'-Favorite-Github-Repositories)

**Comment by NazireAta** [comment]
This is also another repo for this course, from 2017

https://github.com/bounswe/bounswe2017group1

**Comment by mmtftr** [comment]
Closing as all issues have been closed
