### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#334]
# 📚 Documentation
## 📝 Description
Use previous [readme](https://github.com/bounswe/bounswe2024group1/blob/main/archive/README.md) from old repository and create an updated description and contributors of the project.

**Comment by mmtftr** [comment]
I think a restructure is appropriate as the old readme didn't have a very good structure. A ToC would be useful. Open to ideas from everyone here.

**Comment by mmtftr** [comment]
@NazireAta has added an initial README. I will be modifying it with more information about the project this semester.

**Comment by mmtftr** [comment]
#356 has completed this issue. Closing
