### ISSUE TITLE
Functional Requirements: User Management and Authentication

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#336]
# 📚 Documentation
## 📝 Description
Write the functional requirements for user management and authentication. This should include:
- User registration process
- Email/password login functionality
- User profile management (create, edit, delete)
- Follow/unfollow functionality between users

Ensure that each requirement is clear, concise, and testable. Use numbered subsections for organization (e.g., 1.1, 1.2, etc.).

## 🔗 Related Links
- [Requirements Google Doc](https://docs.google.com/document/d/11sfnuuFubBtVJHK5ImGJnsxv02XV4UADdsJBXsu_tbk/edit)

## 👁‍🗨 Reviewer
@asligook

**Comment by EnesBaserr** [comment]
Requirements are determined for User Management & Authentication for now.
