### ISSUE TITLE
Non-Functional Requirements: Performance, Security, and Accessibility

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#341]
# 📚 Documentation
## 📝 Description
Write the non-functional requirements focusing on performance, security, and accessibility. This should include:
- Performance metrics (e.g., response times, concurrent users)
- Security requirements (e.g., authentication, data protection)
- Accessibility requirements based on WCAG 2.2 guidelines
- Any other relevant non-functional requirements (e.g., scalability, reliability)

Ensure that each requirement is clear, measurable, and testable. Use numbered subsections for organization (e.g., 6.1, 6.2, etc.).

## 🔗 Related Links
- [Requirements Google Doc](https://docs.google.com/document/d/11sfnuuFubBtVJHK5ImGJnsxv02XV4UADdsJBXsu_tbk/edit)

## 👁‍🗨 Reviewer
@mmtftr

**Comment by mmtftr** [comment]
Requirements written in Google doc, and moved to [Requirements](https://github.com/bounswe/bounswe2024group1/wiki/Requirements)
