### ISSUE TITLE
Functional Requirements: Personalized Recommendation System

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#345]
# 📚 Documentation
## 📝 Description
Write the functional requirements for the personalized recommendation system to be implemented when displaying questions in relation to tags.

- Personalized ecommendation for the pages that list questions

Ensure that each requirement is clear, concise, and testable.

## 🔗 Related Links
- [Requirements Google Doc](https://docs.google.com/document/d/11sfnuuFubBtVJHK5ImGJnsxv02XV4UADdsJBXsu_tbk/edit)

## 👁‍🗨 Reviewer
@NazireAta

**Comment by ozdentarikcan** [comment]
Wrote personalized recommendation system requirements and updated them according to the feedback received.
