### ISSUE TITLE
Figma UI Design

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#346]
# 🎨 Design
## 📝 Description
The UI Design of the application should be created for the reference of the frontend and mobile teams. Frontend teams must have a proper reference design of the User Interface so that the final product is consistent.

The acceptance criteria are:
- All pages of the application as defined in the Requirements have a design
- Commonly used components among these pages are consistent (ie. have the same design)
- Proper spacing and hierarchy of content are used in the design.
- The Typography and color assets are used instead of arbitrary colors.
- (Optional) Using auto layout is recommended so that the design easily translates into frontend code.

Prototyping is **not** included in this task.

## 🔗 Related Links
- [Link to Figma](https://www.figma.com/design/9DJfcKei60qYIhTtEOWxZI/Semantic-Browse-for-Cuisines-(Copy)?node-id=228-850&node-type=canvas&t=uxdtvJgSY31l3b9h-0)
- [Link to Requirements](https://docs.google.com/document/d/11sfnuuFubBtVJHK5ImGJnsxv02XV4UADdsJBXsu_tbk/edit?usp=sharing)

## 👁‍🗨 Reviewer
@asligook

**Comment by asligook** [comment]
Done with my part in the UI design, waiting for your feedback for additions @NazireAta  <3

**Comment by NazireAta** [comment]
done checking your part @asligook and also completed mine, @ozdentarikcan any updates on scenarios?

**Comment by NazireAta** [comment]
Great! Thanks
