### ISSUE TITLE
Create Scenario and Mockups

### ISSUE THREAD

**Issue by ozdentarikcan** [bounswe/bounswe2024group1#347]
# 🎨 Design
## 📝 Description
Create scenarios and mockups for the project. The scenarios should describe specific personas and their activities in the system. Mockups will be created to illustrate users' actions in the system according to the scenarios.

## 🔗 Related Links
- [Scenario Mockups](https://github.com/bounswe/bounswe2024group1/wiki/Scenario-Mockups)
## 👁‍🗨 Reviewer
@reviewer

**Comment by NazireAta** [comment]
Related Issues:

- [ ] #349 
- [ ] #350
- [ ] #351 
- [ ] #352

**Comment by NazireAta** [comment]
@ozdentarikcan could you add screenshots from our [Figma UI Design](https://www.figma.com/design/9DJfcKei60qYIhTtEOWxZI/Semantic-Browse-for-Cuisines-(Copy)?node-id=128-278&node-type=canvas&t=zzVraJOSiC5pen0R-0) to the scenarios wiki page?

**Comment by NazireAta** [comment]
Great work ppl!
