### ISSUE TITLE
Create Class Diagrams

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#352]
# 📚 Documentation
## 📝 Description
Create class diagrams for our project to demonstrate the object classes and the associations between classes.

## 👁‍🗨 Reviewer
@Cgtycolak

**Comment by atakanyasar** [comment]
Created User, Question, Answer, Tag, QuestionVote, AnswerVote classes, added their functions and some basic relations
https://app.diagrams.net/#G1zA3Jx5Lm9HvZ41KHNUTcYI22U8Qi0IIE

**Comment by EnesBaserr** [comment]
Completed for now. Closing this issue.
