### ISSUE TITLE
[Frontend] Implement Tag Page

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#362]
# 📌 Implement a Feature
## 🏡 Component 
- [ ] Backend
- [X] Frontend
- [ ] Mobile
- [ ] Design
- [ ] Documentation 
- [ ] Other

## 📚 Description
Tag Page will display tag-related information to the user, this task aims to implement it in frontend.

Important Note : This issue aims to implement the Tag Page will mock data for the 1-st milestone customer presentation demo, it will be improved in the future parts of the project.

## 📋 Acceptance Criteria
- [] The tag page design is implemented as in the UI design and allows the user to see information about the related tag.

## 📃 Related requirements
> 1.5. Tag Page\
> 1.5.1. Basics \
> 1.5.1.1. All Users shall be able to view information about the Tag such as;
> 1.5.1.1.1. its description in Wikidata,
> 1.5.1.1.2. a link to its Wikipedia page if it exists,
> 1.5.1.1.3. its file extension if it exists,
> 1.5.1.1.4. its photo if it exists,
> 1.5.1.1.5. its Author(s) if any,
> 1.5.1.1.6. Inception (wikidata data point) if it exists 
> 1.5.1.2. All Users shall be able to view an image associated with the Tag.
> 1.5.1.2.1. The image is the “logo image” in Wikidata if it exists.
> 1.5.2. Question Listing
> 1.5.2.1. All Users shall be able to view “Top Rated” Questions for a Tag.
> 1.5.2.2. All Users shall be able to view “Recent” Questions for a Tag.
> 1.5.2.2.1 Recent is defined as reverse chronological order.
> 1.5.3. Interaction
> 1.5.3.1. Registered Users shall be able to follow and unfollow a Tag
> 1.5.3.2. Registered Users shall be able to create a new Question linked to the Tag from the Tag Page

### 📅 Deadline
- **Estimated hours of work**: 2 hours
- **Implementation Deadline:** October 21
- **Review Deadline:** October 22  

## 👁‍🗨 Reviewer
@NazireAta

**Comment by asligook** [comment]
Closed by #419
