### ISSUE TITLE
[Frontend] Implement Profile Page

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#364]
# 📌 Implement a Feature
## 🏡 Component 
- [x] Frontend

## 📚 Description
Implement Profile page according to the design with an add question edit profile, question and answer list.

## 📋 Acceptance Criteria
- [x] The Profile page shows the profile information of the user.
- [x] The Profile page lists questions and answers

## 📃 Related requirements
[Link to section](https://github.com/bounswe/bounswe2024group1/wiki/Requirements#12-profile-page)
> 1.2. Profile Page
> 1.2.1. Basics
> 1.2.1.1. Registered Users shall have a personalized Profile Page.
> 1.2.1.2. All Users shall be able to see the following information for any Registered User:
> 1.2.1.2.1. Reputation Points
> 1.2.1.2.2. Follower count
> 1.2.1.2.3. Following count
> 1.2.1.2.4. Question count
> 1.2.1.2.5. Answer count.

### 📅 Deadline
- **Estimated hours of work**: 4 hours
- **Implementation Deadline:** October 19
- **Review Deadline:** October 22  

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by NazireAta** [comment]
closed due to #412
