### ISSUE TITLE
Create tracker issue template

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#40]
> Thanks for the good work! The existing issue and PR templates look good to me. I have a couple suggestions to increase our productivity here.

> Since we're in the process of adding a lot of documentation and doing planning, it might be good to have templates for those types of tasks. In addition, I think that using tracker issues to track the progress of bigger undertakings is a good practice; so I think it'd be good for us to have a tracker issue template as well.

_Originally posted by @mmtftr in https://github.com/bounswe/bounswe2024group1/issues/13#issuecomment-1952197929_
            
Let's create tracker issue template as well.

**Comment by atakanyasar** [comment]
I checked some of open souce repositories and I could find [this issue in vs-code repo](https://github.com/microsoft/vscode/issues/204292) as an idea.

**Comment by mmtftr** [comment]
> I checked some of open souce repositories and I could find [this issue in vscode repo](https://github.com/microsoft/vscode/issues/204292) as an idea.

I like the categorization and usage of emojis here.
