### ISSUE TITLE
Implement Tests For Auth and User APIs

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#407]
# 📌 Implement a Feature
## 🏡 Component 
-Backend
-Test

## 📚 Description
Unit tests for Authentication and authorization is required

## 📋 Acceptance Criteria
- [ ] auth/login
- [ ] auth/signup
- [ ] /users/me
- [ ] /users/{id}
- [ ] /users/{id}/follow
- [ ] /users/{id}/unfollow

### 📅 Deadline
- **Estimated hours of work**: 2 hours
- **Implementation Deadline:** October 21
- **Review Deadline:** October 22  

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by EnesBaserr** [comment]
Unit tests are implemented for all services. Check #513
