### ISSUE TITLE
[Backend] Implement POST /execute-code API endpoint

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#439]
# 📌 Implement a Feature
## 🏡 Component 
- Backend

## 📚 Description
Request:
```
{
  "code": "string",
  "language": "c",
  "input": "string"
}
```
Response:
```
{
  "status": 200,
  "data": {
    "status": "success",
    "output": "[1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 9]\n",
    "executionTime": 15
  }
}
```

## 📋 Acceptance Criteria
- [x] The response should be correct.
- [x] Should be tested.

## 📃 Related requirements
[Link to section](https://github.com/bounswe/bounswe2024group1/wiki/Requirements#166-code-snippets)
> 1.6.6. Code Snippets \
> 1.6.6.1. Registered Users shall be able to write executable code snippets using special tags. \
> 1.6.6.2. Registered Users shall be able to write in the following Supported Languages: \
> 1.6.6.2.1. C \
> 1.6.6.2.2. C# \
> 1.6.6.2.3. C++ \
> 1.6.6.2.4. Go \
> 1.6.6.2.5. Java \
> 1.6.6.2.6. JavaScript \
> 1.6.6.2.7. Python 3 \
> 1.6.6.3. Registered Users shall be able to execute executable code snippets inside Question descriptions, Answer descriptions, and their Answer preview. \
> 1.6.6.4. Registered Users shall be able to run snippets in other answers and through the preview for their own answer.

### 📅 Deadline
- **Estimated hours of work**: 4 hours
- **Implementation Deadline:** October 27
- **Review Deadline:** October 29  

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by EnesBaserr** [comment]
Closed with linked PR
