### ISSUE TITLE
Create  Scenarios For SIB

### ISSUE THREAD

**Issue by EnesBaserr** [bounswe/bounswe2024group1#50]
# 📌 Create Scenarios
## 📝 Description
Create scenarios and mockups for SIM. The scenarios should describe specific personas and their activities in the system. The mockups are high level drawings of envisioned interactions with the system.

**_Reviewer : @yukseleren_** 

## 📈 Motivation
Different scenarious to provide clear abstraction for project.

**Comment by EnesBaserr** [comment]
Relevant wiki page opened as draft [🔗 **_Scenarios and Mockup Draft_**](https://github.com/bounswe/bounswe2024group1/wiki/Scenarios-and-Mockup-Draft)

**Comment by EnesBaserr** [comment]
Start adding relevant usecases under the [🔗 Mockup and Scenarious wiki-page ](https://github.com/bounswe/bounswe2024group1/wiki/Milestone-Scenarios-&-Mockups)

**Comment by asligook** [comment]
The scenarios and the mockups have been completed and the resulting pages can be seen under this page:  
[Milestone-Scenarios-&-Mockups](https://github.com/bounswe/bounswe2024group1/wiki/Milestone-Scenarios-&-Mockups).
Hence the issue is closed.
