### ISSUE TITLE
[Frontend] Implement Tag Creation Page

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#504]
# 📌 [Frontend] Implement Tag Creation Page
## 🏡 Component 
- [x] Frontend

## 📚 Description
Implement the tag creation interface, validate that user has >50 reputation.

## 📋 Acceptance Criteria
- [ ] Name and description inputs
- [ ] Validation rules per type
- [ ] Validation of user reputation
- [ ] Submit/cancel actions

### 📅 Deadline
- **Estimated hours**: 2 hours

**Comment by asligook** [comment]
Closed by #568.
