### ISSUE TITLE
Tag Milestones to the Issues

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#51]
# 📌 Organize Issues
## 📝 Description
Every issue needs to be associated with a milestone.

## 📈 Motivation
Knowing the requirements for a milestone is essential for planning and tracking a project.

## 📊 Additional context

Reviewer(s): None.

**Comment by boraykasap** [comment]
[Here.](https://github.com/orgs/bounswe/projects/54)
