### ISSUE TITLE
Fix Class Diagram

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#521]
# 📚 Documentation
## 📝 Description
Fix class diagrams according to the feedback we got:

- [ ]  It seems to have copied irrelevant material from the old one.

## Related Pages: 
[Use Case Diagram](https://github.com/bounswe/bounswe2024group1/wiki/Class-Diagram)
## 👁‍🗨 Reviewer
@asligook

**Comment by mmtftr** [comment]
Closed by adding the new class diagram to the [wiki page](https://github.com/bounswe/bounswe2024group1/wiki/Class-Diagram)
