### ISSUE TITLE
Backend - Implement Question Search endpoint

### ISSUE THREAD

**Issue by EnesBaserr** [bounswe/bounswe2024group1#529]
# 📌 Implement a Feature
## 🏡 Component 
- [X] Backend

## 📚 Description
A user can search for questions.

## 📋 Acceptance Criteria
- [X] A user can search for questions.

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by Cgtycolak** [comment]
Closed with [PR](https://github.com/bounswe/bounswe2024group1/pull/555)
