### ISSUE TITLE
Backend Implement GET /users/{userId}/following Endpoint

### ISSUE THREAD

**Issue by EnesBaserr** [bounswe/bounswe2024group1#537]
# 📌 Implement a Feature
## 🏡 Component 
- [X] Backend

## 📚 Description
A user can see users which he/she follows

## 📋 Acceptance Criteria
- [X] A user can see users which he/she follows

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by Cgtycolak** [comment]
Closed with [PR](https://github.com/bounswe/bounswe2024group1/pull/554)
