### ISSUE TITLE
[Backend] Double upvote should error

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#546]
# 🐞 Bug report

## 🏡 Component 
- [x] Backend

## ✅ Expected Behavior
Question upvote/downvote is rejected if it exists

## ❌ Actual Behavior
Instead new votes were created and the vote count was incorrectly updated.

## 🚀 Steps to Reproduce the Problem
1. Upvote a question
2. Upvote it again
3. Observe that votes have increased by 2

## 💻 Specifications

  - Version: `develop`
  - Platform: MacOS 15.1
  - Subsystem: Arc Browser

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by EnesBaserr** [comment]
Also handled for double downvote

**Comment by EnesBaserr** [comment]
Closed with PR
