### ISSUE TITLE
[Backend] Opposite vote should update instead of error

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#547]
# 🐞 Bug report

## 🏡 Component 
- [x] Backend

## ✅ Expected Behavior
After upvoting an answer/question, a downvote should remove the previous upvote and add an upvote.

## ❌ Actual Behavior
Error is returned due to previous vote existing

## 🚀 Steps to Reproduce the Problem
1. Upvote a answer
2. Try to downvote it
3. Observe the error message

## 💻 Specifications

  - Version: `develop`
  - Platform: MacOS 15.1
  - Subsystem: Arc Browser

## 👁‍🗨 Reviewer
@EnesBaserr

**Comment by EnesBaserr** [comment]
Closed with linked PR
