### ISSUE TITLE
Create Mockups for the Scenarios

### ISSUE THREAD

**Issue by asligook** [bounswe/bounswe2024group1#55]
# 📌 Create Mockups for the Scenarios
## 📝 Description
Mockups will be created to illustrate users' actions in the SIB system according to the scenarios.

_Reviewer:_ @yukseleren 

## 📈 Motivation
Mockups will be beneficial for understanding the user actions in the system.
It's a deliverable of the 1st Milestone.

## 📊 Additional context
Figma is chosen as the development tool for this task.

**Comment by EnesBaserr** [comment]
Figma used as a design tool and the draft version completed.

**Comment by EnesBaserr** [comment]
Start adding relevant usecases under the [🔗 Mockup and Scenarious wiki-page ](https://github.com/bounswe/bounswe2024group1/wiki/Milestone-Scenarios-&-Mockups)

**Comment by EnesBaserr** [comment]
@mmtftr started reviewing Mockups.

**Comment by mmtftr** [comment]
Added comments in figma.

**Comment by mmtftr** [comment]
Reviewed. Looks good for closing.

**Comment by asligook** [comment]
The scenarios and the mockups have been completed and the resulting pages can be seen under this page:  
[Milestone-Scenarios-&-Mockups](https://github.com/bounswe/bounswe2024group1/wiki/Milestone-Scenarios-&-Mockups).
Hence the issue is closed.
