### ISSUE TITLE
Create Template for Personal Effort Pages

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#56]
# 📌 Personal Efforts Page Template
## 📝 Description
Template for the personal effort pages with tables for each week, (task, type, estimated time, time taken)

## 📈 Motivation
We need to keep track of everyone's work for this project

## 📊 Additional context

Reviewer: @mmtftr

**Comment by NazireAta** [comment]
created it [here](https://github.com/bounswe/bounswe2024group1/wiki/Personal-Effort-Template)

**Comment by mmtftr** [comment]
looks good to me @NazireAta

**Comment by NazireAta** [comment]
Thanks!
