### ISSUE TITLE
Document Primary Features

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#583]
# 📚 Documentation
## 📝 Description
- Create detailed documentation for primary features like semantic search and user management.
- Include feature descriptions, screenshots, and examples of usage.
- Specify how these features are implemented.
- Link existing commits or planned changes to improve these features.

## :bar_chart: Acceptance Criteria

- [x] Documentation includes a description, implementation, and examples of each feature.
- [ ] Screenshots or relevant visual aids are attached.
- [ ] Feature evaluation criteria (e.g., performance metrics, user feedback).

## 👁‍🗨 Reviewer
@reviewer

**Comment by EnesBaserr** [comment]
[🔗 Workspace](https://github.com/bounswe/bounswe2024group1/wiki/Primary-Features-Checklist)

**Comment by mmtftr** [comment]
Closed by creating [Primary Features Checklist](https://github.com/bounswe/bounswe2024group1/wiki/Primary-Features-Checklist)
