### ISSUE TITLE
Review and Update API Documentation

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#585]
# 📚 Documentation
## 📝 Description

- Document all relevant API endpoints, including:

    - Endpoint URL
    - Input Parameters (with examples)
    - Expected Outputs (with examples)
    - Error Responses
- Ensure API documentation aligns with implemented endpoints.
- Highlight updates in the backend or frontend integrating the APIs.

## :bar_chart: Acceptance Criteria

- [ ] Complete documentation for all endpoints used in the project.
- [ ] Example API calls with inputs and outputs.
- [ ] Linked to relevant backend commits or pull requests.

## 👁‍🗨 Reviewer
@reviewer

**Comment by EnesBaserr** [comment]
Collection added into repo at backend/resources/postman_collection as .json format and will be updating in every change .
