### ISSUE TITLE
Document Project Standards

### ISSUE THREAD

**Issue by NazireAta** [bounswe/bounswe2024group1#586]
# 📚 Documentation
## 📝 Description
- Document WCAG2.2. standards' checklist and acceptance criteria with examples.

## :bar_chart: Acceptance Criteria
- [X] Standard is documented. 
- [X] Acceptance criteria is documented with examples.

## 👁‍🗨 Reviewer
@atakanyasar

**Comment by ozdentarikcan** [comment]
In [Standard Checklist and Examples](https://github.com/bounswe/bounswe2024group1/wiki/WCAG-2.2-Accessibility-Standards-%E2%80%90-Checklist-and-Examples), I documented the acceptance criteria as a checklist, provided examples, checked the completed criteria.
