### ISSUE TITLE
[Frontend] References to Tags and Questions in discussions

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#589]
# 📌 Implement a Feature
## 🏡 Component 
- [X] Frontend

## 📚 Description
For domain-specific features, we want to have the ability to refer to existing Tags like software languages and Questions inside the answer box. It's enough to have a syntax that does this.

One possible solution is to implement a custom react-markdown component for this. (replacing a tags, then postprocessing the anchor tags that have a special url to refer to tags, eg. if href = "#tag-123" then we should have a  link with the id 123, if href = "#q-5" then we should link the Question with the id 5.

## 📋 Acceptance Criteria
- - [X] Syntax for Tag Referencing:
	- [X] A clear and unambiguous syntax for referring to existing Tags must be implemented.
	- [X] Example syntax: [#tag-123] or similar as decided.
- - [X] Rendering of Tags:
	- [X] Tags referenced using the defined syntax should render as clickable links within the answer box.
	- [X] Links should display the associated tag text and not just the ID.
- - [X] React-Markdown Component:
	- [X] The custom React-Markdown component must support replacing anchor tags with a specific href pattern (e.g., "#tag-123") with the appropriate Tag representation.
	- [X] Anchor tags with other URLs or patterns should not be affected.
- - [X] Fallback Handling:
	- [X]  If a referenced Tag ID does not exist:
	- [X]  Render the tag reference in plain text or with a default style (e.g., [#tag-123]) to indicate an unresolved reference.

### 📅 Deadline
- **Estimated hours of work**: 4 days
- **Implementation Deadline:** December 8
- **Review Deadline:** December 10  

## 👁‍🗨 Reviewer
@mmtftr

**Comment by asligook** [comment]
I realized that I have forgotten to close this issue after merge, the implementation is done in [PR #624](https://github.com/bounswe/bounswe2024group1/pull/624) closing the issue.
