### ISSUE TITLE
[Mobile] Implement Bookmark Page

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#607]
## Description

Implement a page that shows the list of bookmarked questions a user has. This page is accessible through the user menu on the top right.

## Relevant requirements
[Link to section](https://github.com/bounswe/bounswe2024group1/wiki/Requirements#144-feed-interaction)

> 1.4.4.3. Registered Users shall be able to bookmark Questions from the Feed.

**Comment by atakanyasar** [comment]
> This page is accessible through the user menu on the top right.

Should this menu be on the profile page?

**Comment by mmtftr** [comment]
yeah sorry for the inaccurate description. we can put it in the profile for mobile
