### ISSUE TITLE
Fix `User` term in the requirements

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#62]
# 🐞 Bug report
## ✅ Expected Behavior
User/Registered User terms should be consistent in the requirements

## ❌ Actual Behavior
It is inconsistent and confusing. We need to better define these terms

Reviewer: @NazireAta

**Comment by mmtftr** [comment]
Completed with revision https://github.com/bounswe/bounswe2024group1/wiki/Requirements/e1fba820ef8932de862c0b04cfb5e730e590193f

**Comment by mmtftr** [comment]
Ready for review @NazireAta

**Comment by NazireAta** [comment]
Looks great!
