### ISSUE TITLE
[Frontend] Show Author for Programming Language Tags

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#636]
# 📌 Implement a Feature
## 🏡 Component 
- [x] Frontend

## 📚 Description
We should show the author of a programming language in its Page as one of the description fields.

## 📋 Acceptance Criteria
- [X] The author's name is shown with an author icon on the left.
- [X] (Accessibility) We have sr-only text that describes this icon: eg. "This programming language was authored by {name}"

## 📃 Related requirements
[Link to section](https://github.com/bounswe/bounswe2024group1/wiki/Requirements#152-programming-language-tag)
>1.5.2. Programming Language Tag
> 1.5.2.1. All Users shall be able to view information about a Programming Language Tag such as;
> 1.5.2.1.1. its description,
> 1.5.2.1.2. its Author(s) if any,
> 1.5.2.1.3. inception year if available,
> 1.5.2.1.4. its file extension if it exists,
> 1.5.2.1.5. a link to its official website,
> 1.5.2.1.6. its Stack Exchange tag if it exists

## 👁‍🗨 Reviewer
@NazireAta

**Comment by asligook** [comment]
Closed by [PR #669  ](https://github.com/bounswe/bounswe2024group1/pull/669)
