### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#64]
# 📌 Feature request 
## 📝 Description
The UI Design of the application should be created for the reference of the frontend and mobile teams.

The acceptance criteria are:
- All pages of the application as defined in the Requirements have a design
- Commonly used components among these pages are consistent (ie. have the same design)
- Proper spacing and hierarchy of content is used in the design.
- The Typography and color assets are used instead of arbitrary colors.
- ~The mockup pages should be edited so that the newly designed components/pages are used.~
- (Optional) Using auto layout is recommended so that the design easily translates into frontend code.

Prototyping is **not** included in this task.

## 📈 Motivation
Frontend teams must have a proper reference design of the User Interface so that the final product is consistent.

## 📊 Additional context
The mockups and scenarios created by @EnesBaserr and @asligook provide a baseline for the functional contents of these designs. However, there might be missing parts and as such [the Requirements](https://github.com/bounswe/bounswe2024group1/wiki/Requirements) are the source of truth and must be referenced throughout this task.

**Comment by mmtftr** [comment]
Figma design file's link has been added to the sidebar of the wiki.

**Comment by mmtftr** [comment]
### Bookmarks Page
<details>
 <summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/8cf8f0f9-9a0a-4bfe-90d5-2c5a188790cf"/>
</details>

### Comments
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/e5cd99ca-da53-4796-96c4-a7b5d79a106e"/>
</details>

### Cuisine Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/abeea79e-8d0b-4122-8e55-89fed71bf3ea"/>
</details>

### Dish Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/91841df0-d96b-44a8-a0bc-b03fe561fb7e"/>
</details>

### Feed Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/0aed15f7-e712-4551-bb33-8e4db2ffd815"/>
</details>

### Filter Modal
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/51c8cdee-76c7-4752-a675-a941f29a05fe"/>
</details>

### Recipe Card
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/e0736343-eccd-454e-b37e-19c479562c3b"/>
</details>

### Recipe Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/d62dc7de-d0f9-45a4-8d15-04b76fd7ba54"/>
</details>

### Dish Card
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/13402668/d2cf7fc8-8fc4-4961-93f6-d897498a74f8"/>
</details>

**Comment by NazireAta** [comment]
### My Profile Page
<details>
 <summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/75906429/3e8613f3-b71f-4cd7-9698-a48eea1eafe3"/>
</details>

### Other User Profile Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/75906429/ea3451fb-7c4d-4dc6-8e99-26cf4e781124"/>
</details>

### Search Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/75906429/9ccba569-970f-4753-a5b9-9e93e8467f24"/>
</details>

### Recipe Creation Page
<details>
<summary>Expand</summary>
<img src="https://github.com/bounswe/bounswe2024group1/assets/75906429/a6fe9b35-9225-4433-9737-a96df87ad770"/>
</details>

**Comment by asligook** [comment]
I have reviewed the UI Design, as far as I see all pages are consistent with the requirements so I will close the issue.
It seems great, thanks for your effort @mmtftr and @NazireAta .
