### ISSUE TITLE
[Documentation] Write Scenario For Final Milestone

### ISSUE THREAD

**Issue by ozdentarikcan** [bounswe/bounswe2024group1#658]
# 📚 Documentation
## 📝 Description
Write the scenario for the final milestone. It should include the usage of both Web and Mobile application extensively.

## 👁‍🗨 Reviewer
@mmtftr

**Comment by ozdentarikcan** [comment]
Fnail Milestone Scenario is [here](https://github.com/bounswe/bounswe2024group1/wiki/Final-Milestone-Scenario), waiting for your feedback @mmtftr!

**Comment by mmtftr** [comment]
Thanks a lot, this looks really nice. I think it's fine for use. Can we make sure it's linked in our lab report and the related lab report issue?
