### ISSUE TITLE
Write Contribution Guide

### ISSUE THREAD

**Issue by mmtftr** [bounswe/bounswe2024group1#70]
# 📌 Feature request 
## 📝 Description
A contribution guide must be written so that members of team agree on the process of merging code.

This is something that must be written by one person but decided on by the whole team, thus this issue includes the discussion with the team and the documentation of the code merging process.

## 📈 Motivation
Efficient code review process is crucial for a software project.

**Comment by mmtftr** [comment]
This was discussed in a team meeting. I will write the draft and post it for review by the team.

**Comment by mmtftr** [comment]
https://github.com/bounswe/bounswe2024group1/wiki/Contribution-Guide

**Comment by mmtftr** [comment]
Added `ARCHITECTURE.md` and `CODEOWNERS` definition.

**Comment by mmtftr** [comment]
Assignin @atakanyasar  for review.

**Comment by atakanyasar** [comment]
It seems great. Maybe, we can also decide on which merge method we will use for pull requests.

**Comment by mmtftr** [comment]
Alright, I'll be adding the merge commit method. We can change later if needed

**Comment by mmtftr** [comment]
@atakanyasar I've added the merge method.

**Comment by atakanyasar** [comment]
Great. Let's close this issue.
