### ISSUE TITLE
[Documentation] Document Customer Feedback for Final Milestone Demo Presentation

### ISSUE THREAD

**Issue by asligook** [bounswe/bounswe2024group1#709]
# 📚 Documentation
## 📝 Description
The customer feedback, asked questions during the final milestone demo will be documented in a Wiki page and used in Milestone Report-3.

## Deadline:
December 20

## 👁‍🗨 Reviewer
@mmtftr

**Comment by ozdentarikcan** [comment]
I documented the customer feedback here: [Customer Feedback for the Milestone‐3 Demo](https://github.com/bounswe/bounswe2024group1/wiki/Customer-Feedback-for-the-Milestone%E2%80%903-Demo)

**Comment by ozdentarikcan** [comment]
Closed as complete.
