### ISSUE TITLE
User Authentication and Authorization	

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#74]
# 📌 Feature request 
## 📝 Description
- Configure authentication mechanisms such as username/password authentication
- Implement endpoints and services to enable user registration, password hashing, and storage of user tokens in the database.
-  Create a login endpoint to authenticate users and generate authentication tokens
## 📈 Motivation
Implementing user authentication and authorization ensures the security and integrity of the application by safeguarding user data, enhancing trust with users, and providing personalized experiences while adhering to compliance standards and allowing for granular control over access to resources.

**Comment by EnesBaserr** [comment]
JWT Authentication filter added and combined with Spring Security filter configs.

**Comment by EnesBaserr** [comment]
JUnit Tests are implemented for authentication controller.

**Comment by EnesBaserr** [comment]
Check PR #75 . Closing this issue.
