### ISSUE TITLE
Dockerize Backend

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#76]
# 📌 Feature request 
## 📝 Description
Configure and connect the application with a database using Docker containers. Docker will be used to create and manage the database container, ensuring consistency and portability across different environments.

- **Dockerfile Creation:** Write a Dockerfile specifying the instructions for building the Docker image
- **MySQL Server:**  Configure and connect the application with a database 
- **Build Docker Image:** Use the Docker CLI to build the Docker image based on the Dockerfile, tagging it with an appropriate version or label for easy identification
- **Containerization:** Run the Docker image as a container, ensuring that the backend application starts successfully within the container environment.
- **Configuration Management:** Configure environment variables, networking, and any other necessary settings to ensure the backend application functions correctly within the Docker container.
- **Testing:** Verify that the Dockerized backend application behaves as expected, including functionality, performance, and compatibility with other services or components.
- **Documentation:** Update project documentation to include instructions for Docker image building, deployment, and usage, ensuring that team members have clear guidance on working with the Dockerized backend.

## 📈 Motivation
Docker allows for easy deployment across different environments, ensuring consistency and eliminating environment-specific configuration issues.

**Comment by EnesBaserr** [comment]
Dockerfile and docker-compose.yaml file implemented. Backend status is tested through containers.

**Comment by EnesBaserr** [comment]
PR #82  merged. Closing this issue.
