### ISSUE TITLE
Deploy Backend

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#77]
# 📌 Feature request 
## 📝 Description
Deploy the backend application as a containerized service on the DigitalOcean cloud platform.

1. DigitalOcean Account Setup
2. #76 Prepare Docker Image
3. Container Registry
4. Deployment Configuration
5. Deployment
7. Monitoring and Logging
8. Documentation

## 📈 Motivation
The backend application will be ready to serve incoming requests from users or frontend applications.

**Comment by EnesBaserr** [comment]
Created a droplet(Ubuntu) in Digitalocean. Connected droplet's shell using SSH, downloaded docker and pulled backend images from Hub.

**Comment by EnesBaserr** [comment]
Dockerfile and docker-compose configurations were successfully completed prior to deployment. The containers have been tested and are running smoothly on the droplet.

**Comment by EnesBaserr** [comment]
Check #82 PR. Closing this
