### ISSUE TITLE
Create Use Case Diagram

### ISSUE THREAD

**Issue by asligook** [bounswe/bounswe2024group1#79]
# 📌 Feature request 
## 📝 Description
Create the use case diagram for our project to demonstrate the interactions between the system and environment. 

## 📈 Motivation
The use case diagram will describe actions within the system from the users' perspective.

## 📊 Additional context
As a team member, if you wish, you can contribute and give feedback :)

**Comment by asligook** [comment]
assigning @mmtftr as the reviewer.

**Comment by mmtftr** [comment]
I've added 7 comments to the Figma file for missing or incorrect parts that I've found @asligook

**Comment by mmtftr** [comment]
Looks good to me

**Comment by mmtftr** [comment]
good to close this issue when you're done adding to the wiki

**Comment by asligook** [comment]
Thanks for the review @mmtftr.
I have uploaded the latest version of the diagram to the corresponding Wiki page, it can be reached from [this link.](https://github.com/bounswe/bounswe2024group1/wiki/Use-Case-Diagram)
Closing the issue.
