### ISSUE TITLE
Mobile Implementation Tracker

### ISSUE THREAD

**Issue by YigitMemceroktay** [bounswe/bounswe2024group1#84]
# 🔍 Issue Tracker

## 📝 Description
This issue is to manage and track the development of the tasks for the mobile side.
## 📅 Deadline
28/04/2024
## 🎯 Issues
| Issue | Descripiton | Deadline | Status |
| ----- | ----------- | ------ | ---- |
| #[86](https://github.com/bounswe/bounswe2024group1/issues/86) | Implement the Design for the Search Bar| 28/04/2024 | ⏳ |
| #[85](https://github.com/bounswe/bounswe2024group1/issues/85) |Implement the Design for the User Authentication Page | 28/04/2024 | ⏳ |

**Comment by EnesBaserr** [comment]
Closed due to new term.
