### ISSUE TITLE
Fix Feed Page in UI Design

### ISSUE THREAD

**Issue by asligook** [bounswe/bounswe2024group1#94]
# 🐞 Bug report
## ✅ Expected Behavior
In the requirements specification, there are 2 types of feed: Explore and Following.

## ❌ Actual Behavior
In the UI Design for Feed Page, there are 2 sections as "Top Rated" and "Recent". 

## 🚀 Steps to Reproduce the Problem
1. Update design from the Figma.
2. Upload the updated image of the page.

Reviewer : @mmtftr

**Comment by mmtftr** [comment]
## Fixed Page
![Feed Page](https://github.com/bounswe/bounswe2024group1/assets/13402668/0782345c-e8c9-4f70-a644-b9c9be064c32)

**Comment by mmtftr** [comment]
Awaiting review @asligook

**Comment by asligook** [comment]
@mmtftr, thanks, you are so fast :) I think it seems correct.

**Comment by mmtftr** [comment]
Thanks a lot, closing.
